server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Cualquier ruta no encontrada vuelve a index.html (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Assets deben cargarse normal
    location /assets/ {
        try_files $uri =404;
    }
}
